In [1]:
import pandas as pd

In [2]:
url="https://raw.githubusercontent.com/josevalladares99/etl-data-pipeline-25-2432-2022/refs/heads/main/Data/raw/C_clientes.csv"

In [3]:
df=pd.read_csv(url)
df.head()

  id_cliente            cliente                  correo        ciudad
0      CL100   Comercial Díaz 0  cliente065@empresa.com     Santa Ana
1      CL101      Grupo Ideal 1    cliente131@correo.sv  San Salvador
2      CL102      Grupo Ideal 2  cliente211@empresa.com    San Miguel
3      CL103  Almacenes Prado 3    cliente329@gmail.com     Santa Ana
4      CL104    Soluciones CR 4    cliente441@gmail.com   La Libertad

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  155 non-null    object
 1   cliente     155 non-null    object
 2   correo      152 non-null    object
 3   ciudad      155 non-null    object
dtypes: object(4)
memory usage: 5.0+ KB

In [10]:
df.isnull().sum()

id_cliente    0
cliente       0
correo        3
ciudad        0
dtype: int64

In [11]:
df[df.duplicated()]

    id_cliente                  cliente                  correo       ciudad
150      CL104          Soluciones CR 4    cliente441@gmail.com  La Libertad
151      CL216  Distribuciones Luna 116         correo_invalido  La Libertad
152      CL102            Grupo Ideal 2  cliente211@empresa.com   San Miguel
153      CL123        Servicios Alfa 23   cliente2338@correo.sv    Santa Ana
154      CL223       Tienda Central 123         correo_invalido   San Miguel

In [12]:
print(df['ciudad'].unique())

['Santa Ana' 'San Salvador' 'San Miguel' 'La Libertad']

Limpieza de datos

In [14]:
df = df.drop_duplicates()

In [15]:
df[df.duplicated()]

Empty DataFrame
Columns: [id_cliente, cliente, correo, ciudad]
Index: []

In [13]:
import re

def es_valido(correo):
    if isinstance(correo, str):
        patron = r"^[\w\.-]+@[\w\.-]+\.\w+$"
        return re.match(patron, correo) is not None
    return False

Separar validos y rechazados

In [17]:
validos = df[df['correo'].apply(es_valido)]

rechazados = df[~df['correo'].apply(es_valido)]

Motivo rechazo

In [18]:
def motivo(row):
    motivos = []
    if pd.isna(row['correo']) or not isinstance(row['correo'], str):
        motivos.append("correo_nulo")
    elif '@' not in str(row['correo']):
        motivos.append("correo_sin_arroba")
    elif not re.search(r"\.\w+$", str(row['correo'])):
        motivos.append("correo_sin_dominio")
    return ".".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

/tmp/ipykernel_1066/2525637330.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

Exportar archivos

In [19]:
validos.to_csv("clientes_curated.csv", index=False)
rechazados.to_csv("clientes_rejects.csv", index=False)

In [20]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:oBPWTDnwlDkov4SzFc8zpJwu1kTOiolN@dpg-d6qu7s450q8c73bpf590-a.oregon-postgres.render.com/etl_seguros_k3sp"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 94.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [21]:
validos.to_sql("clientes_curated", con=engine, if_exists="replace", index=False)
rechazados.to_sql("clientes_rejects", con=engine, if_exists="replace", index=False)

18

In [22]:
pd.read_sql(
"SELECT * FROM clientes_curated LIMIT 10",
engine
)

  id_cliente                cliente                  correo        ciudad
0      CL100       Comercial Díaz 0  cliente065@empresa.com     Santa Ana
1      CL101          Grupo Ideal 1    cliente131@correo.sv  San Salvador
2      CL102          Grupo Ideal 2  cliente211@empresa.com    San Miguel
3      CL103      Almacenes Prado 3    cliente329@gmail.com     Santa Ana
4      CL104        Soluciones CR 4    cliente441@gmail.com   La Libertad
5      CL105  Distribuciones Luna 5  cliente592@empresa.com     Santa Ana
6      CL106          Grupo Ideal 6  cliente619@outlook.com  San Salvador
7      CL107      Almacenes Prado 7   cliente75@empresa.com  San Salvador
8      CL108         Empresa Nova 8  cliente861@outlook.com     Santa Ana
9      CL109  Distribuciones Luna 9    cliente998@correo.sv   La Libertad

In [23]:
pd.read_sql(
"SELECT * FROM clientes_rejects LIMIT 10",
engine
)

,id_cliente,cliente,correo,ciudad,motivo_rechazo
0,CL115,Almacenes Prado 15,correo_invalido,San Salvador,correo_sin_arroba
1,CL118,Distribuciones Luna 18,cliente1882correo.sv,La Libertad,correo_sin_arroba
2,CL136,Soluciones CR 36,correo_invalido,La Libertad,correo_sin_arroba
3,CL140,Importadora del Valle 40,cliente4088correo.sv,San Salvador,correo_sin_arroba
4,CL152,Grupo Ideal 52,correo_invalido,San Salvador,correo_sin_arroba
5,CL162,Soluciones CR 62,cliente6211correo.sv,San Miguel,correo_sin_arroba
6,CL176,Distribuciones Luna 76,None,Santa Ana,correo_nulo
7,CL180,Servicios Alfa 80,correo_invalido,Santa Ana,correo_sin_arroba
8,CL181,Comercial Díaz 81,cliente819outlook.com,Santa Ana,correo_sin_arroba
9,CL187,Empresa Nova 87,correo_invalido,La Libertad,correo_sin_arroba

In [24]:
from google.colab import files
files.download("clientes_curated.csv")
files.download("clientes_rejects.csv")